apiVersion: app.cloudclub.com/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: application-sample
    app.kubernetes.io/part-of: cloud-club-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloud-club-operator
  name: application-sample
spec:
  app:
    replicas: 2
    containerName: nginx
    image: nginx:latest
    containerPort: 80
